#!/usr/bin/env python3
"""Generate a starter scaffold for the `custom_backend` auth slot.

`core/auth/auth-providers.ts` throws a clear error for `NEXT_PUBLIC_AUTH_PROVIDER=
custom_backend` until a project runs this script and wires the generated
adapter into that resolver — see the docstring there.

Usage:
    python tool/generate_custom_auth_scaffold.py your_backend
    python tool/generate_custom_auth_scaffold.py your_backend --with-example-module
    python tool/generate_custom_auth_scaffold.py your_backend --with-integration-test

Generates:
    - core/auth/adapters/<slug>/<slug>-auth-adapter.ts
        Implements the real `AuthAdapter` interface
        (core/auth/auth-adapter.ts): checkSession/login/logout/refresh, all
        returning Result<T, ApiError>. Method bodies are TODO stubs — a
        scaffold is *expected* to have implementation gaps; that's the point.
    - examples/app-modules/<slug>-auth/<slug>-auth-example.tsx (--with-example-module)
        Minimal Client Component showing how to wire the adapter.
    - test/core/auth/adapters/<slug>-auth-adapter.test.ts (--with-integration-test)
        Placeholder test with real structure; backend-call assertions marked TODO.

The template ships with no `core/auth/adapters/` directory by default — it is
only created when a project runs this script.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ADAPTERS_DIR = ROOT / "core" / "auth" / "adapters"
EXAMPLES_DIR = ROOT / "examples" / "app-modules"
TEST_DIR = ROOT / "test" / "core" / "auth" / "adapters"


def validate_slug(value: str) -> str:
    slug = value.strip().lower()
    if not re.fullmatch(r"[a-z][a-z0-9_]*", slug):
        raise SystemExit(f"backend name must be snake_case, got: {value!r}")
    return slug


def snake_to_kebab(slug: str) -> str:
    return slug.replace("_", "-")


def snake_to_pascal(slug: str) -> str:
    return "".join(part.capitalize() for part in slug.split("_") if part)


def render_adapter(slug: str) -> str:
    kebab = snake_to_kebab(slug)
    class_name = f"{snake_to_pascal(slug)}AuthAdapter"
    return f"""import type {{ Result, ApiError }} from '@/core/network/api-result';
import type {{ AuthAdapter, AuthSession }} from '@/core/auth/auth-adapter';

/**
 * Scaffolded `custom_backend` adapter for `{slug}`, generated by
 * `tool/generate_custom_auth_scaffold.py`. Fill in the TODOs below with real
 * calls to your backend/SDK, then register this class for the
 * `'custom_backend'` case in `core/auth/auth-providers.ts`:
 *
 *   case 'custom_backend':
 *     return new {class_name}();
 *
 * Every method must keep returning `Result<T, ApiError>` — never throw for
 * an expected failure (bad credentials, expired session, network error).
 * See core/network/api-result.ts.
 */
export class {class_name} implements AuthAdapter {{
  async checkSession(): Promise<Result<AuthSession | null, ApiError>> {{
    // TODO({slug}): call your backend/SDK to resolve the current session.
    // Return `{{ ok: true, value: null }}` when there is no session — never throw.
    return {{ ok: true, value: null }};
  }}

  async login(_credentials: unknown): Promise<Result<AuthSession, ApiError>> {{
    // TODO({slug}): call your backend/SDK's login endpoint with `_credentials`.
    return {{
      ok: false,
      error: {{ message: '{class_name}.login is not implemented yet.' }},
    }};
  }}

  async logout(): Promise<Result<void, ApiError>> {{
    // TODO({slug}): call your backend/SDK's logout/sign-out endpoint.
    return {{ ok: true, value: undefined }};
  }}

  async refresh(): Promise<Result<void, ApiError>> {{
    // TODO({slug}): call your backend/SDK's token/session refresh endpoint.
    return {{ ok: true, value: undefined }};
  }}
}}
"""


def render_example_module(slug: str) -> str:
    kebab = snake_to_kebab(slug)
    class_name = snake_to_pascal(slug)
    return f"""'use client';

/**
 * Minimal example wiring for the generated `{slug}` custom auth adapter.
 * Not imported anywhere by default — copy the pattern into your own
 * feature/page once `{class_name}AuthAdapter` has a real implementation.
 */
import {{ useState }} from 'react';
import {{ {class_name}AuthAdapter }} from '@/core/auth/adapters/{slug}/{kebab}-auth-adapter';

export function {class_name}AuthExample() {{
  const [status, setStatus] = useState<string>('idle');

  async function handleCheckSession() {{
    setStatus('checking...');
    const adapter = new {class_name}AuthAdapter();
    const result = await adapter.checkSession();
    setStatus(result.ok ? JSON.stringify(result.value) : result.error.message);
  }}

  return (
    <div className="space-y-2">
      <button type="button" onClick={{handleCheckSession}}>
        Check {slug} session
      </button>
      <p>{{status}}</p>
    </div>
  );
}}
"""


def render_integration_test(slug: str) -> str:
    kebab = snake_to_kebab(slug)
    class_name = snake_to_pascal(slug)
    return f"""import {{ describe, expect, it }} from 'vitest';
import {{ {class_name}AuthAdapter }} from '@/core/auth/adapters/{slug}/{kebab}-auth-adapter';

/**
 * Placeholder integration test for the generated `{slug}` auth adapter.
 * Structure is real (imports the real adapter, asserts the real Result
 * shape) but the actual backend-call assertions are TODO until
 * `{class_name}AuthAdapter` has a real implementation — see
 * core/auth/adapters/{slug}/{kebab}-auth-adapter.ts.
 */
describe('{class_name}AuthAdapter', () => {{
  it('checkSession() returns a Result without throwing', async () => {{
    const adapter = new {class_name}AuthAdapter();
    const result = await adapter.checkSession();
    expect(result.ok).toBe(true);
    // TODO({slug}): once checkSession() calls your real backend, assert
    // against a mocked fetch/SDK response instead of the scaffold default.
  }});

  it.todo('login() authenticates against the real {slug} backend');
  it.todo('logout() clears the real {slug} session');
  it.todo('refresh() renews the real {slug} session');
}});
"""


def write_file(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("backend_name", help="snake_case backend/integration name, e.g. clerk or your_backend")
    parser.add_argument(
        "--with-example-module",
        action="store_true",
        help="also generate a minimal example Client Component under examples/app-modules/",
    )
    parser.add_argument(
        "--with-integration-test",
        action="store_true",
        help="also generate a placeholder test under test/core/auth/adapters/",
    )
    args = parser.parse_args()

    slug = validate_slug(args.backend_name)
    kebab = snake_to_kebab(slug)

    outputs: list[Path] = []

    adapter_path = ADAPTERS_DIR / slug / f"{kebab}-auth-adapter.ts"
    if adapter_path.exists():
        raise SystemExit(f"{adapter_path.relative_to(ROOT)} already exists — remove it first or pick a different name")
    outputs.append(write_file(adapter_path, render_adapter(slug)))

    if args.with_example_module:
        example_path = EXAMPLES_DIR / f"{kebab}-auth" / f"{kebab}-auth-example.tsx"
        outputs.append(write_file(example_path, render_example_module(slug)))

    if args.with_integration_test:
        test_path = TEST_DIR / f"{kebab}-auth-adapter.test.ts"
        outputs.append(write_file(test_path, render_integration_test(slug)))

    print(f"Generated custom_backend auth scaffold for {slug!r}:")
    for path in outputs:
        print(f"  {path.relative_to(ROOT)}")
    print()
    print(
        "Next: implement the TODOs, then register it in "
        "core/auth/auth-providers.ts under the 'custom_backend' case."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
